---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/kroche-co/argocd-cluster.git
        revision: HEAD
        directories:
          - path: cluster/*
          - path: cluster/*/_pre
          - path: cluster/*/_post
  template:
    metadata:
      name: >-
        {{- if (regexMatch "^_(pre|post)$" .path.basename) -}}
        {{ .path.basenameNormalized }}--{{ index .path.segments (sub (len .path.segments) 2) | normalize }}
        {{- else -}}
        main--{{ .path.basenameNormalized }}
        {{- end -}}
      annotations:
        argocd.argoproj.io/sync-wave: >-
          {{- if eq .path.basename "_pre" -}}
          -10
          {{- else if eq .path.basename "_post" -}}
          10
          {{- else -}}
          0
          {{- end -}}
    spec:
      destination:
        namespace: >-
          {{- if (regexMatch "^_(pre|post)$" .path.basename) -}}
          {{ index .path.segments (sub (len .path.segments) 2) | normalize -}}
          {{- else if not (hasPrefix "_" .path.basename) -}}
          {{ .path.basenameNormalized -}}
          {{- end -}}
        server: "https://kubernetes.default.svc"
      project: default
      sources:
        - path: "{{ .path.path }}"
          repoURL: https://github.com/kroche-co/argocd-cluster.git
          targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 5
            maxDuration: 10m
