---
createAggregateRoles: true
configs:
  params:
    application.namespaces: "*"
  repositories:
    argocd-cluster:
      type: "git"
      url: "https://github.com/kroche-co/argocd-cluster.git"
      project: "default"
controller:
  clusterAdminAccess:
    enabled: true
server:
  clusterAdminAccess:
    enabled: true
repoServer:
  clusterAdminAccess:
    enabled: true
dex:
  enabled: false
